# Generated by Django 4.1.5 on 2023-02-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useracount', '0002_alter_accounts_first_name_alter_accounts_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('firm_name', models.CharField(max_length=100)),
                ('services', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('useracount.accounts',),
        ),
    ]
