# Generated by Django 4.1.5 on 2023-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracount', '0004_accounts_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='ADMIN', max_length=50),
        ),
    ]
