# Generated by Django 4.1.5 on 2023-03-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_appointment_end_hour_appointment_start_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_hour',
        ),
    ]
