# Generated by Django 4.1.5 on 2023-03-11 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_appointment_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(choices=[(datetime.date(2023, 3, 12), '2023-03-12'), (datetime.date(2023, 3, 13), '2023-03-13'), (datetime.date(2023, 3, 14), '2023-03-14'), (datetime.date(2023, 3, 15), '2023-03-15'), (datetime.date(2023, 3, 16), '2023-03-16'), (datetime.date(2023, 3, 17), '2023-03-17'), (datetime.date(2023, 3, 18), '2023-03-18')])),
                ('collection_timeslot', models.IntegerField(choices=[(0, '09:00 - 09:30 AM'), (1, '10:00 - 10:30 AM'), (2, '11:00 - 11:30 AM'), (3, '12:00 - 12:30 PM'), (4, '01:00 - 01:30 PM'), (5, '14:00 - 14:30 PM'), (6, '15:00 - 15:30 PM'), (7, '16:00 - 16:30 PM'), (8, '17:00 - 17:30 PM')])),
                ('delivery_date', models.DateField(editable=False)),
                ('delivery_timeslot', models.IntegerField(choices=[(0, '09:00 - 09:30 AM'), (1, '10:00 - 10:30 AM'), (2, '11:00 - 11:30 AM'), (3, '12:00 - 12:30 PM'), (4, '01:00 - 01:30 PM'), (5, '14:00 - 14:30 PM'), (6, '15:00 - 15:30 PM'), (7, '16:00 - 16:30 PM'), (8, '17:00 - 17:30 PM')])),
            ],
        ),
    ]
