# Generated by Django 4.1.5 on 2023-03-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.appointment'),
        ),
    ]
