# Generated by Django 4.1.5 on 2023-03-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_appointment_cloth_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Accepted', 'Accepted'), ('Laundary', 'Laundary'), ('Ironing', 'Ironing'), ('Completed', 'Completed')], default='Unassigned', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentclothes', to='Booking.appointment')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.dispatchbooking')),
            ],
        ),
    ]
