# Generated by Django 4.1.5 on 2023-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_clothorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothorder',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
