# Generated by Django 4.1.5 on 2023-04-17 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_clothorder_dispatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchbooking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 11, 14, 38, 218194)),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
