# Generated by Django 4.1.5 on 2023-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_dispatchbooking_canceled_dispatchbooking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
