# Generated by Django 4.1.5 on 2023-05-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0016_clothorder_booking_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchbooking',
            old_name='Appointment',
            new_name='appointment',
        ),
    ]
