# Generated by Django 4.1.5 on 2023-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0019_remove_appointment_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
